/** US states + cities para el selector de dirección del paciente */

export const US_STATES: { code: string; name: string }[] = [
  { code: 'AL', name: 'Alabama' },
  { code: 'AK', name: 'Alaska' },
  { code: 'AZ', name: 'Arizona' },
  { code: 'AR', name: 'Arkansas' },
  { code: 'CA', name: 'California' },
  { code: 'CO', name: 'Colorado' },
  { code: 'CT', name: 'Connecticut' },
  { code: 'DE', name: 'Delaware' },
  { code: 'FL', name: 'Florida' },
  { code: 'GA', name: 'Georgia' },
  { code: 'HI', name: 'Hawaii' },
  { code: 'ID', name: 'Idaho' },
  { code: 'IL', name: 'Illinois' },
  { code: 'IN', name: 'Indiana' },
  { code: 'IA', name: 'Iowa' },
  { code: 'KS', name: 'Kansas' },
  { code: 'KY', name: 'Kentucky' },
  { code: 'LA', name: 'Louisiana' },
  { code: 'ME', name: 'Maine' },
  { code: 'MD', name: 'Maryland' },
  { code: 'MA', name: 'Massachusetts' },
  { code: 'MI', name: 'Michigan' },
  { code: 'MN', name: 'Minnesota' },
  { code: 'MS', name: 'Mississippi' },
  { code: 'MO', name: 'Missouri' },
  { code: 'MT', name: 'Montana' },
  { code: 'NE', name: 'Nebraska' },
  { code: 'NV', name: 'Nevada' },
  { code: 'NH', name: 'New Hampshire' },
  { code: 'NJ', name: 'New Jersey' },
  { code: 'NM', name: 'New Mexico' },
  { code: 'NY', name: 'New York' },
  { code: 'NC', name: 'North Carolina' },
  { code: 'ND', name: 'North Dakota' },
  { code: 'OH', name: 'Ohio' },
  { code: 'OK', name: 'Oklahoma' },
  { code: 'OR', name: 'Oregon' },
  { code: 'PA', name: 'Pennsylvania' },
  { code: 'RI', name: 'Rhode Island' },
  { code: 'SC', name: 'South Carolina' },
  { code: 'SD', name: 'South Dakota' },
  { code: 'TN', name: 'Tennessee' },
  { code: 'TX', name: 'Texas' },
  { code: 'UT', name: 'Utah' },
  { code: 'VT', name: 'Vermont' },
  { code: 'VA', name: 'Virginia' },
  { code: 'WA', name: 'Washington' },
  { code: 'WV', name: 'West Virginia' },
  { code: 'WI', name: 'Wisconsin' },
  { code: 'WY', name: 'Wyoming' },
  { code: 'DC', name: 'Washington D.C.' },
];

export const CITIES_BY_STATE: Record<string, string[]> = {
  AL: ['Alabaster','Albertville','Alexander City','Anniston','Athens','Auburn','Bessemer','Birmingham','Cullman','Daphne','Decatur','Dothan','Enterprise','Fairhope','Florence','Gadsden','Homewood','Hoover','Huntsville','Jacksonville','Jasper','Madison','Mobile','Montgomery','Muscle Shoals','Northport','Opelika','Oxford','Pelham','Phenix City','Prattville','Prichard','Scottsboro','Selma','Talladega','Troy','Tuscaloosa'],
  AK: ['Anchorage','Badger','College','Fairbanks','Juneau','Ketchikan','Kodiak','Sitka','Wasilla'],
  AZ: ['Apache Junction','Avondale','Buckeye','Bullhead City','Casa Grande','Casas Adobes','Catalina Foothills','Chandler','Flagstaff','Gilbert','Glendale','Goodyear','Maricopa','Mesa','Peoria','Phoenix','Prescott','Queen Creek','Scottsdale','Sierra Vista','Surprise','Tempe','Tucson','Yuma'],
  AR: ['Bentonville','Conway','El Dorado','Fayetteville','Fort Smith','Hot Springs','Jonesboro','Little Rock','North Little Rock','Pine Bluff','Rogers','Russellville','Sherwood','Springdale','Texarkana','West Memphis'],
  CA: ['Anaheim','Antioch','Bakersfield','Berkeley','Burbank','Chula Vista','Clovis','Compton','Corona','Costa Mesa','Daly City','El Monte','Elk Grove','Escondido','Fontana','Fremont','Fresno','Fullerton','Garden Grove','Glendale','Hayward','Huntington Beach','Inglewood','Irvine','Lancaster','Long Beach','Los Angeles','Modesto','Moreno Valley','Murrieta','Norwalk','Oakland','Oceanside','Ontario','Orange','Oxnard','Palmdale','Pasadena','Pomona','Rancho Cucamonga','Rialto','Richmond','Riverside','Roseville','Sacramento','Salinas','San Bernardino','San Diego','San Francisco','San Jose','San Mateo','Santa Ana','Santa Clara','Santa Clarita','Santa Rosa','Simi Valley','Spokane','Stockton','Sunnyvale','Thousand Oaks','Torrance','Vallejo','Victorville','Visalia'],
  CO: ['Arvada','Aurora','Boulder','Brighton','Broomfield','Castle Rock','Colorado Springs','Commerce City','Denver','Fort Collins','Grand Junction','Greeley','Highlands Ranch','Lakewood','Longmont','Loveland','Parker','Pueblo','Thornton','Westminster'],
  CT: ['Bridgeport','Bristol','Danbury','East Hartford','Greenwich','Hartford','Manchester','Meriden','Milford','New Britain','New Haven','Norwalk','Stamford','Stratford','Waterbury','West Hartford'],
  DE: ['Dover','Newark','Wilmington'],
  FL: ['Boca Raton','Bonita Springs','Cape Coral','Clearwater','Coral Springs','Davie','Deerfield Beach','Deltona','Fort Lauderdale','Fort Myers','Gainesville','Hialeah','Hollywood','Homestead','Jacksonville','Jupiter','Kissimmee','Lakeland','Lauderhill','Miramar','Miami','Miami Beach','Miami Gardens','Naples','North Port','Orlando','Palm Bay','Palm Beach Gardens','Pembroke Pines','Pensacola','Plantation','Pompano Beach','Port St. Lucie','Sarasota','Spring Hill','St. Petersburg','Sunrise','Tallahassee','Tampa','West Palm Beach'],
  GA: ['Albany','Alpharetta','Athens','Atlanta','Augusta','Columbus','Gainesville','Johns Creek','Macon','Marietta','Peachtree City','Roswell','Sandy Springs','Savannah','Smyrna','South Fulton','Valdosta','Warner Robins'],
  HI: ['East Honolulu','Hilo','Honolulu','Kailua','Kaneohe','Pearl City','Waipahu'],
  ID: ['Boise','Caldwell','Coeur d\'Alene','Idaho Falls','Lewiston','Meridian','Moscow','Nampa','Pocatello','Post Falls','Twin Falls'],
  IL: ['Aurora','Bloomington','Champaign','Chicago','Cicero','Decatur','Elgin','Evanston','Joliet','Naperville','Peoria','Rockford','Springfield','Waukegan'],
  IN: ['Anderson','Bloomington','Carmel','Columbus','Evansville','Fishers','Fort Wayne','Gary','Hammond','Indianapolis','Kokomo','Lafayette','Lawrence','Muncie','Noblesville','South Bend','Terre Haute'],
  IA: ['Ames','Cedar Rapids','Council Bluffs','Davenport','Des Moines','Dubuque','Iowa City','Sioux City','Waterloo'],
  KS: ['Kansas City','Lawrence','Lenexa','Olathe','Overland Park','Salina','Topeka','Wichita'],
  KY: ['Bowling Green','Covington','Elizabethtown','Lexington','Louisville','Owensboro','Paducah','Richmond'],
  LA: ['Baton Rouge','Bossier City','Kenner','Lafayette','Lake Charles','Metairie','Monroe','New Orleans','Shreveport'],
  ME: ['Auburn','Augusta','Bangor','Lewiston','Portland','South Portland'],
  MD: ['Annapolis','Baltimore','Bowie','Frederick','Gaithersburg','Germantown','Rockville','Silver Spring','Waldorf'],
  MA: ['Boston','Brockton','Cambridge','Fall River','Lowell','Lynn','New Bedford','Newton','Quincy','Springfield','Waltham','Worcester'],
  MI: ['Ann Arbor','Clinton','Dearborn','Detroit','Flint','Grand Rapids','Kalamazoo','Lansing','Livonia','Macomb','Rochester Hills','Southfield','Sterling Heights','Warren','Westland'],
  MN: ['Bloomington','Brooklyn Park','Burnsville','Coon Rapids','Duluth','Eagan','Eden Prairie','Edina','Maple Grove','Minneapolis','Plymouth','Rochester','St. Cloud','St. Paul','Woodbury'],
  MS: ['Biloxi','Gulfport','Hattiesburg','Jackson','Meridian','Southaven','Tupelo'],
  MO: ['Columbia','Independence','Jefferson City','Joplin','Kansas City','Lee\'s Summit','O\'Fallon','Springfield','St. Charles','St. Joseph','St. Louis'],
  MT: ['Billings','Bozeman','Great Falls','Helena','Kalispell','Missoula'],
  NE: ['Bellevue','Grand Island','Lincoln','Omaha'],
  NV: ['Carson City','Enterprise','Henderson','Las Vegas','North Las Vegas','Reno','Sparks','Spring Valley','Sunrise Manor'],
  NH: ['Concord','Manchester','Nashua'],
  NJ: ['Camden','Edison','Elizabeth','Jersey City','Newark','Paterson','Toms River','Trenton','Woodbridge'],
  NM: ['Albuquerque','Las Cruces','Rio Rancho','Roswell','Santa Fe'],
  NY: ['Albany','Bronx','Brooklyn','Buffalo','Cheektowaga','Hempstead','Islip','Manhatan','Manhattan','New York City','Niagara Falls','Queens','Rochester','Schenectady','Staten Island','Syracuse','Utica','Yonkers'],
  NC: ['Asheville','Cary','Chapel Hill','Charlotte','Concord','Durham','Fayetteville','Gastonia','Greensboro','High Point','Jacksonville','Raleigh','Wilmington','Winston-Salem'],
  ND: ['Bismarck','Fargo','Grand Forks','Minot'],
  OH: ['Akron','Canton','Cincinnati','Cleveland','Columbus','Dayton','Elyria','Hamilton','Lorain','Parma','Springfield','Toledo','Youngstown'],
  OK: ['Broken Arrow','Edmond','Lawton','Moore','Norman','Oklahoma City','Stillwater','Tulsa'],
  OR: ['Beaverton','Bend','Eugene','Gresham','Hillsboro','Medford','Portland','Salem','Springfield'],
  PA: ['Allentown','Bethlehem','Erie','Lancaster','Philadelphia','Pittsburgh','Reading','Scranton'],
  RI: ['Cranston','Pawtucket','Providence','Warwick','Woonsocket'],
  SC: ['Charleston','Columbia','Florence','Greenville','Mount Pleasant','North Charleston','Rock Hill','Spartanburg'],
  SD: ['Aberdeen','Rapid City','Sioux Falls'],
  TN: ['Chattanooga','Clarksville','Jackson','Johnson City','Kingsport','Knoxville','Memphis','Murfreesboro','Nashville'],
  TX: ['Abilene','Allen','Amarillo','Arlington','Austin','Beaumont','Brownsville','Carrollton','Corpus Christi','Dallas','Denton','El Paso','Fort Worth','Frisco','Garland','Grand Prairie','Houston','Irving','Killeen','Laredo','League City','Lewisville','Lubbock','McAllen','McKinney','Mesquite','Midland','Missouri City','Odessa','Pasadena','Pearland','Plano','Richardson','Round Rock','San Antonio','Sugar Land','Tyler','Waco'],
  UT: ['Alpine','Alta','Altamont','Alton','Amalga','American Fork','Annabella','Antimony','Aurora','Beaver','Benjamin','Benson','Blanding','Bluffdale','Boulder','Bountiful','Brian Head','Brigham City','Castle Dale','Cedar City','Cedar Hills','Centerfield','Centerville','Charleston','Circleville','Clarkston','Clawson','Clearfield','Clinton','Coalville','Corinne','Cornish','Cottonwood Heights','Daniel','Delta','Draper','Duchesne','Eagle Mountain','East Carbon','Elk Ridge','Elmo','Elsinore','Elwood','Emery','Enoch','Enterprise','Ephraim','Erda','Escalante','Eureka','Fairfield','Fairview','Farmington','Farr West','Ferron','Fillmore','Fountain Green','Francis','Fruit Heights','Garland','Genola','Glendale','Glenwood','Goshen','Green River','Gunnison','Harrisville','Heber City','Helper','Herriman','Highland','Hildale','Holden','Holladay','Honeyville','Hooper','Huntington','Huntsville','Hurricane','Hyde Park','Hyrum','Independence','Ivins','Joseph','Junction','Kamas','Kanab','Kanarraville','Kaysville','Layton','Leamington','Leeds','Lehi','Levan','Lewiston','Lindon','Logan','Lyman','Lynndyl','Magna','Manti','Mantua','Mapleton','Marysvale','Mayfield','Meadow','Mendon','Midvale','Midway','Milford','Millville','Minersville','Moab','Mona','Monroe','Monticello','Morgan','Moroni','Mount Pleasant','Murray','Myton','Naples','Nephi','New Harmony','Newton','North Logan','North Ogden','North Salt Lake','Oak City','Oakley','Ogden','Ophir','Orangeville','Orderville','Orem','Panguitch','Park City','Parowan','Payson','Perry','Plain City','Pleasant Grove','Pleasant View','Price','Providence','Provo','Randolph','Richfield','Richmond','River Heights','Riverdale','Riverton','Roosevelt','Roy','Rush Valley','Salem','Salina','Salt Lake City','Sandy','Santa Clara','Santaquin','Saratoga Springs','Scipio','Sigurd','Smithfield','South Jordan','South Ogden','South Salt Lake','South Weber','Spanish Fork','Springdale','Springville','St. George','Sterling','Stockton','Sunnyside','Sunset','Syracuse','Tooele','Toquerville','Tremonton','Trenton','Uintah','Vernal','Vernon','Vineyard','Virgin','Washington','Washington Terrace','Wellington','Wellsville','Wendover','West Bountiful','West Haven','West Jordan','West Point','West Valley City','Willard','Woodland Hills','Woods Cross'],
  VT: ['Burlington','Montpelier','Rutland'],
  VA: ['Alexandria','Arlington','Chesapeake','Hampton','Lynchburg','Newport News','Norfolk','Portsmouth','Raleigh','Richmond','Roanoke','Suffolk','Virginia Beach'],
  WA: ['Bellevue','Bellingham','Federal Way','Kirkland','Marysville','Redmond','Renton','Seattle','Spokane','Tacoma','Vancouver','Yakima'],
  WV: ['Charleston','Huntington','Morgantown','Parkersburg','Wheeling'],
  WI: ['Appleton','Green Bay','Kenosha','Madison','Milwaukee','Oshkosh','Racine','Waukesha'],
  WY: ['Casper','Cheyenne','Laramie'],
  DC: ['Washington'],
};
