'use client';

import { useEffect } from 'react';

/**
 * Registers the Service Worker generated by @serwist/next.
 *
 * On the very first visit to a new PWA, the SW installs *after* Chrome has
 * already evaluated installability, so `beforeinstallprompt` never fires that
 * first load. We fix this by reloading once (sessionStorage flag) after the SW
 * first activates — on the reloaded page the SW is already controlling the
 * document and Chrome fires `beforeinstallprompt` normally.
 */
export function SWRegister(): null {
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (!('serviceWorker' in navigator)) return;
    if (process.env.NODE_ENV !== 'production') return;

    const SW_RELOAD_KEY = 'sw-first-activated';

    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .then((reg) => {
        if (reg.installing && !sessionStorage.getItem(SW_RELOAD_KEY)) {
          reg.installing.addEventListener('statechange', function () {
            if ((this as unknown as { state: string }).state === 'activated') {
              sessionStorage.setItem(SW_RELOAD_KEY, '1');
              window.location.reload();
            }
          });
        }
      })
      .catch((err) => {
        console.error('[SW] registration failed', err);
      });
  }, []);

  return null;
}
