'use client';

import { useEffect } from 'react';

/**
 * Registers the Service Worker generated by @serwist/next.
 *
 * @serwist/next v9 does NOT auto-inject registration code. The SW
 * file is built at /sw.js but it remains dormant until the browser
 * calls navigator.serviceWorker.register(). Without registration,
 * Chrome considers the app non-installable, so beforeinstallprompt
 * never fires and Chrome DevTools reports "no manifest detected"
 * even when the manifest link tag is present.
 *
 * Mount once in the root layout. Idempotent — safe across reloads
 * because the browser dedupes identical registrations.
 */
export function SWRegister(): null {
  useEffect(() => {
    if (typeof window === 'undefined') return;
    if (!('serviceWorker' in navigator)) return;
    // Only register in production; dev builds skip the SW (disable in
    // next.config.ts), and trying to register a non-existent /sw.js in
    // dev produces a confusing 404 in console.
    if (process.env.NODE_ENV !== 'production') return;

    navigator.serviceWorker
      .register('/sw.js', { scope: '/' })
      .catch((err) => {
        // Non-fatal — the app still works, just no offline / no
        // installability. Log for diagnostics.
        // eslint-disable-next-line no-console
        console.error('[SW] registration failed', err);
      });
  }, []);

  return null;
}
